feat(http-client.ts): adds http client
cytechmobile/radicle-planning-boards pull request #12
Opened 2023-11-24 13:04 UTC by carboniq-dev

2023-11-28 15:26 UTC, maninak requested changes
I understand this is draft as of writing this, but I'll be sharing some early feedback to ensure we're progressing in the right direction.

Also regarding the conventional commit context, no need to be very detailed. In fact it's better to be more general when using a context so that it can be reused. E.g. instead of `httpd.ts` we can just use `httpd` for any change in that file or any other file that is related to httpd (typings, error handling, whatever). Besides it makes it easier to decide what context to use, especially given that commits commonly change more than one files.

It would also be a good idea to merge `main` branch on yours after many of the open PRs are merged.

2023-11-29 09:25 UTC, carboniq-dev commented on nuxt.config.ts
> +      apiBase: '/server-url',
I was planning on closing this PR one anyway especially because I didnt care about any conventions.

2023-11-29 09:28 UTC, carboniq-dev commented on nuxt.config.ts
> +      apiBase: '/server-url',
Initially this was meant to start the discussion but we're passed that already

2023-12-01 16:13 UTC, carboniq-dev commented
obsolete

2023-12-01 16:13 UTC, closed without merging