docs(changelog): update changelog
cytechmobile/radicle-planning-boards pull request #81
Opened 2024-07-02 06:14 UTC by QZera

2024-07-02 07:08 UTC, maninak requested changes

2024-07-02 07:08 UTC, maninak commented on CHANGELOG.md
> +- Add container packaging
```suggestion
- Add docker container packaging configuration
```

2024-07-02 07:08 UTC, maninak commented on CHANGELOG.md
> +- Add support for filtering via a text field
We could and perhaps should say more about this and its subfeatures.

For example that it searches titles and ids, that it does partial string matching, that it highlights on the card exactly which part of it matched, the keyboard shortcut, the escape key to unfocus, and anything else I'm forgetting.

2024-07-02 16:19 UTC, QZera commented on CHANGELOG.md
> +- Add container packaging
Done!

2024-07-02 19:52 UTC, maninak approved these changes
Approved with proposed changes. Choose your destiny.

2024-07-02 19:52 UTC, maninak commented on CHANGELOG.md
> +  - Visually highlights the matched part(s) on the cards
```suggestion
  - Visually highlights on each card the matched substring(s)
```

2024-07-02 19:52 UTC, maninak commented on CHANGELOG.md
> +  - Visually highlights the matched part(s) on the cards
Nit αλλά επειδή είναι σημαντικό feature και το proposed copy το κάνει market είπα να το γράψω.

2024-07-02 19:52 UTC, maninak commented on CHANGELOG.md
> +  - Syncs the filterbox value with the URL for enhanced shareability
```suggestion
  - filtering state synced with and driven by the URL means that any links you copy at any time and send to others will result in the same cards shown on their screen
```

kinda on the nose but whatever :P

2024-07-03 05:38 UTC, QZera commented on CHANGELOG.md
> +  - Visually highlights the matched part(s) on the cards
Done!

2024-07-03 05:39 UTC, QZera commented on CHANGELOG.md
> +  - Syncs the filterbox value with the URL for enhanced shareability
👍 done

2024-07-03 05:41 UTC, QZera commented
Updated changelog as suggested, updated date, updated version

2024-07-03 10:09 UTC, maninak approved these changes

2024-07-03 10:29 UTC, merged